#!/bin/bash
# 3161
# RULE             : Cron logging must be implemented in RHEL 8.
# QUESTION_TEXT    : Verify that "rsyslog" is configured to log cron events with the following command:

# Note: If another logging package is used, substitute the utility configuration file for "/etc/rsyslog.conf" or "/etc/rsyslog.d/*.conf" files.

# $ sudo grep -s cron /etc/rsyslog.conf /etc/rsyslog.d/*.conf

# /etc/rsyslog.conf:*.info;mail.none;authpriv.none;cron.none                          /var/log/messages
# /etc/rsyslog.conf:# Log cron stuff
# /etc/rsyslog.conf:cron.*                                                                                                    /var/log/cron

# If the command does not return a response, check for cron logging all facilities with the following command.

# $ sudo grep -s /var/log/messages /etc/rsyslog.conf /etc/rsyslog.d/*.conf

# /etc/rsyslog.conf:*.info;mail.none;authpriv.none;cron.none                          /var/log/messages

# If "rsyslog" is not logging messages for the cron facility or all facilities, this is a finding.

check_v_230387 () {
    local finding=0

    echo "Checking for rsyslog cron logging ..."
    if ! grep -s cron /etc/rsyslog.conf /etc/rsyslog.d/*.conf | grep -vE ^*#; then
        echo "Nothing found in /etc/rsyslog.*"
        finding=1
    else
        if ! grep -s /var/log/messages /etc/rsyslog.conf /etc/rsyslog.d/*.conf | grep -vE ^*#; then
            ehco "No logging set!!"
            finding=1
        fi
    fi

    return $finding

}


check_v_230387