#!/bin/bash

# 4521
# QUESTION_ID      : ocil:navy.navwar.niwcatlantic.scc.rhel8os:question:4521
# RULE             : RHEL 8 must allocate audit record storage capacity to store at least one week of audit records, when audit records are not immediately sent to a central audit record storage facility.
# QUESTION_TEXT    : Verify RHEL 8 allocates audit record storage capacity to store at least one week of audit records when audit records are not immediately sent to a central audit record storage facility.

# Determine to which partition the audit records are being written with the following command:

# $ sudo grep -iw log_file /etc/audit/auditd.conf
# log_file = /var/log/audit/audit.log

# Check the size of the partition to which audit records are written (with the example being /var/log/audit/) with the following command:

# $ sudo df -h /var/log/audit/
# /dev/sda2 24G 10.4G 13.6G 43% /var/log/audit

# If the audit records are not written to a partition made specifically for audit records (/var/log/audit is a separate partition), determine the amount of space being used by other files in the partition with the following command:

# $ sudo du -sh [audit_partition]
# 1.8G /var/log/audit

# If the audit record partition is not allocated for sufficient storage capacity, this is a finding.

# Note: The partition size needed to capture a week of audit records is based on the activity level of the system and the total storage capacity available. Typically 10.0 GB of storage space for audit records should be sufficient.

check_v_230476 () {
    local finding=0

    dir=$(grep -iw log_file /etc/audit/auditd.conf | cut -d' ' -f 3)
    min="10G"
    read partition size <<<"$(df --output='target,size' "$dir" | tail -1 )"

    echo "$dir is located in filesystem  $partition  , $size"

    if [ ! "$partition" == "/var/log/audit" ]; then
        echo "$dir is NOT its own PARTITION, resides in $partition"
        finding=1
    fi

    echo "MIN: $min, CURRENT: $size"

    if (( ${size%G} < ${min%G})) ;then
        echo "storage is TOO SMALL"
        finding=1
    fi

    return $finding


}

check_v_230476
