#!/bin/bash

# 2041
# RULE             : All RHEL 8 local files and directories must have a valid owner.
# QUESTION_TEXT    : Verify all local files and directories on RHEL 8 have a valid owner with the following command:

# Note: The value after -fstype must be replaced with the filesystem type.  XFS is used as an example.

# $ sudo find / -fstype xfs -nouser

# If any files on the system do not have an assigned owner, this is a finding.

# Note: Command may produce error messages from the /proc and /sys directories.

check_v_230326 () {
    local finding=0
    #EXCLUDE VIRTUAL FS AND OVERLAY FS (not host local)
    find / -xdev \( -path /proc -o -path /sys -o -path /run -o -path /var/lib/docker \) -prune -o -nouser -print > tmp.txt
    if [ -s tmp.txt ];then
        echo "The following DO NOT HAVE AN ASSIGNED OWNER"
        cat tmp.txt
        finding=1
    fi

    return $finding

}

check_v_230326