#!/bin/bash

# 2041
# RULE             : All RHEL 8 local files and directories must have a valid owner.
# QUESTION_TEXT    : Verify all local files and directories on RHEL 8 have a valid owner with the following command:

# Note: The value after -fstype must be replaced with the filesystem type.  XFS is used as an example.

# $ sudo find / -fstype xfs -nouser

# If any files on the system do not have an assigned owner, this is a finding.

# Note: Command may produce error messages from the /proc and /sys directories.

