#!/bin/bash
# 4681
# QUESTION_ID      : ocil:navy.navwar.niwcatlantic.scc.rhel8os:question:4681
# RULE             : RHEL 8 must securely compare internal information system clocks at least every 24 hours with a server synchronized to an authoritative time source, such as the United States Naval Observatory (USNO) time servers, or a time server designated for the appropriate DoD network (NIPRNet/SIPRNet), and/or the Global Positioning System (GPS).
# QUESTION_TEXT    : Verify RHEL 8 is securely comparing internal information system clocks at least every 24 hours with an NTP server with the following commands:

# $ sudo grep maxpoll /etc/chrony.conf

# server 0.us.pool.ntp.mil iburst maxpoll 16

# If the "maxpoll" option is set to a number greater than 16 or the line is commented out, this is a finding.

# Verify the "chrony.conf" file is configured to an authoritative DoD time source by running the following command:

# $ sudo grep -i server /etc/chrony.conf
# server 0.us.pool.ntp.mil

# If the parameter "server" is not set or is not set to an authoritative DoD time source, this is a finding.

#"\s" = ANY WHITESPACE CHARACTER

check_v_230484 () {
    local finding=0

    echo "Please double check server entry in /etc/chrony.conf"
    maxpoll=$(grep -Ei '^\s*server.*maxpoll' /etc/chrony.conf  | grep -Po 'maxpoll\s+\d+'| cut -d' ' -f 2)

    #IF YOU WANT TO USE '||' OR '-o' , you need to DOUBLE [[ ]]

    if [[ -z "$maxpoll" -o "$maxpoll" -gt 16 ]];then
        echo "MAXPOLL NOT SET CORRECTLY : $maxpoll"
        finding=1
    fi

    return $finding


}

check_v_230484