#!/bin/bash

# 1721
# RULE             : RHEL 8 must disable kernel dumps unless needed.
# QUESTION_TEXT    : Verify that kernel core dumps are disabled unless needed with the following command:

# $ sudo systemctl status kdump.service

# kdump.service - Crash recovery kernel arming
# Loaded: loaded (/usr/lib/systemd/system/kdump.service; enabled; vendor preset: enabled)
# Active: active (exited) since Mon 2020-05-04 16:08:09 EDT; 3min ago
# Main PID: 1130 (code=exited, status=0/SUCCESS)

# If the "kdump" service is active, ask the System Administrator if the use of the service is required and documented with the Information System Security Officer (ISSO).

# If the service is active and is not documented, this is a finding.

#SYSTEMCTL STATUS on an ACTIVE RETURNS 0
#ON A DISABLED/INACTIVE SERVICE RETURNS NON ZERO

check_v_230310 () {
    local finding=0
    if systemctl status kdump.service --no-pager; then
        finding=1
    fi

    return $finding
}


check_v_230310