#!/bin/bash
# 2061
# QUESTION_ID      : ocil:navy.navwar.niwcatlantic.scc.rhel8os:question:2061
# RULE             : All RHEL 8 local files and directories must have a valid group owner.
# QUESTION_TEXT    : Verify all local files and directories on RHEL 8 have a valid group with the following command:

# Note: The value after -fstype must be replaced with the filesystem type.  XFS is used as an example.

# $ sudo find / -fstype xfs -nogroup

# If any files on the system do not have an assigned group, this is a finding.

# Note: Command may produce error messages from the /proc and /sys directories.
#DONT CHECK THE VIRTUAL FS
# These are virtual or pseudo filesystems, not real files stored on disk.

# Files and directories in /proc, /sys, /run, and /dev are dynamically created by the kernel, not owned by users in the normal sense.

# Many of them may appear unowned or inaccessible — but that’s expected behavior, not a security issue.



check_v_230327 () {
    local finding=0
    #LOCAL FILES AND DIRS
    #EXCLUDE VIRTUAL FS AND OVERLAY FS (not host local)
    # These are virtual or pseudo filesystems, not real files stored on disk.

    # Files and directories in /proc, /sys, /run, and /dev are dynamically created by the kernel, not owned by users in the normal sense.

    # Many of them may appear unowned or inaccessible — but that’s expected behavior, not a security issue.
    find / -xdev \( -path /proc -o -path /sys -o -path /run -o -path /var/lib/docker \) -prune -o -nogroup -print > tmp.txt

    if [ -s tmp.txt ];then
        echo "The following DO NOT HAVE AN ASSIGNED GROUP"
        cat tmp.txt
        finding=1
        rm tmp.txt
    fi

    return $finding

}

check_v_230327