#!/bin/bash

# 4621
# QUESTION_ID      : ocil:navy.navwar.niwcatlantic.scc.rhel8os:question:4621
# RULE             : RHEL 8 must encrypt the transfer of audit records off-loaded onto a different system or media from the system being audited.
# QUESTION_TEXT    : Verify the operating system encrypts audit records off-loaded onto a different system or media from the system being audited with the following commands:

# $ sudo grep -i '$DefaultNetstreamDriver' /etc/rsyslog.conf /etc/rsyslog.d/*.conf

# /etc/rsyslog.conf:$DefaultNetstreamDriver gtls

# If the value of the "$DefaultNetstreamDriver" option is not set to "gtls" or the line is commented out, this is a finding.

# $ sudo grep -i '$ActionSendStreamDriverMode' /etc/rsyslog.conf /etc/rsyslog.d/*.conf

# /etc/rsyslog.conf:$ActionSendStreamDriverMode 1

# If the value of the "$ActionSendStreamDriverMode" option is not set to "1" or the line is commented out, this is a finding.

# If neither of the definitions above are set, ask the System Administrator to indicate how the audit logs are off-loaded to a different system or media.

# If there is no evidence that the transfer of the audit logs being off-loaded to another system or media is encrypted, this is a finding.

check_v_230481 () {
    local finding=0
    #needs to be gtls
    check1=$(grep -si '$DefaultNetstreamDriver' /etc/rsyslog.conf /etc/rsyslog.d/*.conf | grep -vE '^*#' | cut -d' ' -f 2)



    if [ $? -ne 0 ]; then
        echo "\$DefaultNetstreamDriver ENTRY NOT FOUND"
        finding=1
    else
        if [ ! "$check1" = "gtls" ]; then
            echo "\$DefaultNetstreamDriver needs to be gtls, val: $check1"
            finding=1
        fi
    fi

    [ $finding -ne 0 ] && return $finding

    #needs to be 1
    check2=$(grep -si '$ActionSendStreamDriverMode' /etc/rsyslog.conf /etc/rsyslog.d/*.conf | grep -vE '^*#'  | cut -d' ' -f 2)

    if [ $? -ne 0 ]; then
        echo '$ActionSendStreamDriverMode NOT FOUND'
        finding=1
    else
        if [ ! "$check2" == "1" ]; then
            echo "\$ActionSendStreamDriverMode needs to be 1 , val: $check2"
            finding=1
        fi
    fi

    return $finding

}

check_v_230481