#!/bin/bash

#641

# V-230254 - Ensure OpenSSL uses FIPS-approved crypto
# QUESTION_ID: ocil:navy.navwar.niwcatlantic.scc.rhel8os:question:641

check_v_230254() {
    local finding=0
    local openssl_file="/etc/pki/tls/openssl.cnf"
    local expected_include=".include /etc/crypto-policies/back-ends/opensslcnf.config"

    if [ ! -f "$openssl_file" ]; then
        echo "Missing $openssl_file"
        finding=1
    fi

    if grep -Fq "$expected_include" "$openssl_file"; then
        echo "Found OpenSSL policy include in $openssl_file"
    else
        echo "Missing include, Expected: $expected_include"
        finding=1
    fi


    echo "Checking if crypto policy is set to FIPS..."
    current_policy=$(update-crypto-policies --show 2>/dev/null)
    if [[ "$current_policy" == "FIPS" ]]; then
        echo "System-wide crypto policy is FIPS"
    else
        echo "Crypto policy is NOT FIPS"
        echo "Found: $current_policy"
        finding=1
    fi

    return $finding
}

check_v_230254
