#!/bin/bash

# 4321
# RULE             : Successful/unsuccessful modifications to the faillock log file in RHEL 8 must generate an audit record.
# QUESTION_TEXT    : Verify RHEL 8 generates an audit record when successful/unsuccessful modifications to the "faillock" file occur. First, determine where the faillock tallies are stored with the following commands:

# For RHEL versions 8.0 and 8.1:

# $ sudo grep -i pam_faillock.so /etc/pam.d/system-auth

# auth     required          pam_faillock.so preauth dir=/var/log/faillock silent deny=3 fail_interval=900 even_deny_root

# For RHEL versions 8.2 and newer:

# $ sudo grep dir /etc/security/faillock.conf

# dir=/var/log/faillock

# Using the location of the faillock log file, check that the following calls are being audited by performing the following command to check the file system rules in "/etc/audit/audit.rules":

# $ sudo grep -w faillock /etc/audit/audit.rules

# -w /var/log/faillock -p wa -k logins

# If the command does not return a line, or the line is commented out, this is a finding.

check_v_230466 () {
    local finding=0
    dir=$(grep dir /etc/security/faillock.conf  | grep -vE ^# | cut -d' ' -f 3)
    echo "DEFAULT DIR: $dir"
    if ! grep -w "$dir" /etc/audit/audit.rules; then
        echo "NO watch rule for faillock $dir"
        finding=1
    fi
    return $finding
}

check_v_230466