#!/bin/bash

# 2901
# QUESTION_ID      : ocil:navy.navwar.niwcatlantic.scc.rhel8os:question:2901
# RULE             : RHEL 8 must automatically expire temporary accounts within 72 hours.
# QUESTION_TEXT    : Verify temporary accounts have been provisioned with an expiration date of 72 hours.

# For every existing temporary account, run the following command to obtain its account expiration information:

#      $ sudo chage -l <temporary_account_name> | grep -i "account expires"

# Verify each of these accounts has an expiration date set within 72 hours.
# If any temporary accounts have no expiration date set or do not expire within 72 hours, this is a finding.
