#!/bin/bash
#1561

#FOR MY CASE, HOME DIRECTORIES ARE FOUND AND MOUNTED FROM AN NFS SERVER


# RHEL 8 must prevent code from being executed on file systems that contain user home directories.
# QUESTION_TEXT    : Verify file systems that contain user home directories are mounted with the "noexec" option.

# Note: If a separate file system has not been created for the user home directories (user home directories are mounted under "/"), this is automatically a finding as the "noexec" option cannot be used on the "/" system.

# Find the file system(s) that contain the user home directories with the following command:

# $ sudo awk -F: '($3>=1000)&&($7 !~ /nologin/){print $1,$3,$6}' /etc/passwd

# smithj:1001: /home/smithj
# robinst:1002: /home/robinst

# Check the file systems that are mounted at boot time with the following command:

# $ sudo more /etc/fstab

# UUID=a411dc99-f2a1-4c87-9e05-184977be8539 /home ext4 rw,relatime,discard,data=ordered,nosuid,nodev,noexec 0 2

# If a file system found in "/etc/fstab" refers to the user home directory file system and it does not have the "noexec" option set, this is a finding.

check_v_230302 () {

    local finding=0

    finding=$(mount -t nfs,nfs4 | awk '$3 ~ "^/home/" && $0 !~ /noexec/ { print "1" }')

    if [ $finding -eq 1 ];then
        echo "HOME  dirs MISSING NOEXEC (NFS)"
    fi

    exit $finding


}