#!/bin/bash

check_v_230229 () {
    local finding=$(check_PKI)
    #CHECK config.sh for USE_PKI , SET IF APPLICABLE

    if [ -f /etc/sssd/pki/sssd_auth_ca_db.pem ]; then
        echo "FILE EXISTS"
    else
        echo "FILE NOT FOUND"
        return 1
    fi

    openssl x509 -in /etc/sssd/pki/sssd_auth_ca_db.pem -noout -issuer -subject -enddate 2>/dev/null | grep -i "dod root" || echo "DOD ROOT NOT FOUND" && finding=1

    return $finding
}

check_v_230229
#

#OUTPUT
# openssl x509 -in /etc/sssd/pki/sssd_auth_ca_db.pem -noout -issuer -subject -enddate 2>/dev/null | grep -i "dod root"

# issuer=C = US, O = U.S. Government, OU = DoD, OU = PKI, CN = DoD Root CA 6
# subject=C = US, O = U.S. Government, OU = DoD, OU = PKI, CN = DoD Root CA 6
