#!/bin/bash

# 1701
# RULE             : Local RHEL 8 initialization files must not execute world-writable programs.
# QUESTION_TEXT    : Verify that local initialization files do not execute world-writable programs.

# Check the system for world-writable files.

# The following command will discover and print world-writable files. Run it once for each local partition [PART]:

# $ sudo find [PART] -xdev -type f -perm -0002 -print

# For all files listed, check for their presence in the local initialization files with the following commands:

# Note: The example will be for a system that is configured to create user home directories in the "/home" directory.

# $ sudo grep <file> /home/*/.*

# If any local initialization files are found to reference world-writable files, this is a finding.
################################################

check_v_230309 () {
    local finding=0
    local WWFILE="RESULTS/WWFILES.$(date +%Y-%m-%d)"
    local dir=$(pwd)
    #this creates the file at SIZE 0!!!
    #Better than echo '' > file , which creates at size 1
    > $WWFILE
    #local partitions/filesystems
    fs=$(findmnt -D -t notmpfs,devtmpfs,bpf,none,selinuxfs,iso9660,tracefs | awk 'NR>1 {print $7 }')

    while IFS='' read -r mount; do
        echo "CHECKING $mount "
        #- on the -0002 IMPORTANT, Basically saying AT LEAST 0002.
        find "$mount" -xdev -type f -perm -0002 -print | tee -a $WWFILE > /dev/null

    done <<< "$fs"
    #<<< , OPERATOR CALLED "HERE STRING" allows you t pass a string drectly into standard input of a command o loop, like if it were comming from a file or pipe

    #check if file is ECMPTY, run a size check?
    if [ -s $WWFILE ]; then
        finding=1
        fullpath=$(realpath $WWFILE)
        echo "Please see: $fullpath for list of WORLD WRITABLE FILES"
        echo "Possible fix: xargs -a $fullpath -I{} chmod o-w {} "

    fi

    exit $finding



}

check_v_230309

