#!/bin/bash

# 5441
# RULE             : RHEL 8 must block unauthorized peripherals before establishing a connection.
# QUESTION_TEXT    : Verify the USBGuard has a policy configured with the following command:

# $ sudo usbguard list-rules

# If the command does not return results or an error is returned, ask the SA to indicate how unauthorized peripherals are being blocked.
# If there is no evidence that unauthorized peripherals are being blocked before establishing a connection, this is a finding.

# If the USBGuard package is not installed, ask the SA to indicate how unauthorized peripherals are being blocked.
# If there is no evidence that unauthorized peripherals are being blocked before establishing a connection, this is a finding.

# If the system is a virtual machine with no virtual or physical USB peripherals attached, this is not a finding.

check_v_230524 () {
    local finding=0


#   Will grep for ANY string, if none (no rules) is found then fail

    if usbguard is-active && usbguard list-rules | grep -q .; then
        echo "Rules Are PRESENT"
    else
        finding=1
        echo "NO RULES PRESENT!!"
    fi

    return $finding

}

check_v_230524