#!/bin/bash
#Using [[:space:]] as its more posix compatible
#If it find it it will exit with 0
#but regardlesss comments should output
cat /etc/issue

grep -i "^[[:space:]]*Banner[[:space:]]" /etc/ssh/sshd_config | grep -v "^#" | grep /etc/issue && grep -Fq "You are accessing a U.S. Government (USG) Information System" /etc/issue
